### ISSUE TITLE
How to stop all audio in background? (Audio Overlap Issue)

### ISSUE THREAD

**Issue by strong84** [tumtumtum/StreamingKit#110]
I created a demo app with a tableview of a list of mp3 URLs.
when tap on 1st cell, it jumps to ViewController 1 and plays audio automatically.
then I go back to tableview, the audio is still playing, which is what I expect.
But tap on another cell to jump to another ViewController, the audio from ViewControler 1 will not stop. and two audios overlap with each other.

How to stop previous audio once user tap on another cell?

**Comment by arashzeinoddini** [comment]
I created this class method:

`+ (id)sharedSTKAudioPlayer
{
    static STKAudioPlayer *sharedStkAudioPlayer = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        
        NSError* error;
        Float32 bufferLength = 0.1;
        
        [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:&error];
        [[AVAudioSession sharedInstance] setActive:YES error:&error];
        [[AVAudioSession sharedInstance] setPreferredIOBufferDuration:bufferLength error:&error];
        
        sharedStkAudioPlayer = [[STKAudioPlayer alloc] initWithOptions:(STKAudioPlayerOptions){ .flushQueueOnSeek = YES, .enableVolumeMixer = NO, .equalizerBandFrequencies = {50, 100, 200, 400, 800, 1600, 2600, 16000} }];
        sharedStkAudioPlayer.meteringEnabled = YES;
        sharedStkAudioPlayer.volume = 1;
        
    });
    
    return sharedStkAudioPlayer;
}`

and then to use it:
`STKAudioPlayer *  audioPlayer = [STKAudioPlayer sharedSTKAudioPlayer];`
