### ISSUE TITLE
Can I play a song from the media library with StreamingKit?

### ISSUE THREAD

**Issue by dymx101** [tumtumtum/StreamingKit#115]
Hey, 

I use StreamingKit to play both remote & local music files, everything is okay until I want to access a song from the media library with it.

My question is as the title described, can StreamingKit play a song from the iPhone media library? 

The URL from the media library is some thing like:

ipod-library://item/item.mp3?id=2019962417554774664

Thanks!

**Comment by chandandubey** [comment]
Hey,

I use StreamingKit to play both remote & local music files,  and its play fine in background , but when i play another song , the first also playing and multiple song play at a time and how can i stop previously played song
