### ISSUE TITLE
How do I skip to the next song in a queue?

### ISSUE THREAD

**Issue by k3zi** [tumtumtum/StreamingKit#118]
I have a queue of http data sources and I would like to go to the next item. I'm not sure I'm seeing methods for this. Is this implemented?

**Comment by kristoff2016** [comment]
Hello 
I got message: STKHTTPDataSource dealloc 
I have cleared queue  but if when I clicked next song twice and fast then it will show message: STKHTTPDataSource dealloc  
so All song it play all I mean it is delay before I cleared
