### ISSUE TITLE
m3u8 playback

### ISSUE THREAD

**Issue by akatreyt** [tumtumtum/StreamingKit#125]
Using

[audioPlayer play:@"http://playlists.ihrhls.com/c1/2257/playlist.m3u8"]

I get an error and the url wont stream. Sure I'm missing something, any suggestions?

Thanks

**Comment by hutchy** [comment]
@akatreyt I'd be also very much interested in this, if you have the time to fork or share etc.

**Comment by akatreyt** [comment]
yeah, let me see what I can put together in the next few days. stay tuned.

**Comment by akatreyt** [comment]
created pull request 

https://github.com/tumtumtum/StreamingKit/pull/184

if there are any issues let me know and I can fix.

**Comment by akatreyt** [comment]
@hutchy @christophberlin here is a branch that does m3u files, the m3u8 is not working at the moment, not sure on why, I may have time in the next week to look, If I get it working I'll report back. 

https://github.com/akatreyt/StreamingKit/tree/m3u

**Comment by hutchy** [comment]
Thanks! Look forward to seeing your efforts.
