### ISSUE TITLE
Controlling HTTP buffer size

### ISSUE THREAD

**Issue by alecgorge** [tumtumtum/StreamingKit#133]
My users have be complaining that since I switched to StreamingKit, rebuffering has been occurring several times per song when before it didn't.

What is the best way to ensure that more of the track is preloaded (in the event of poor network connection)? Is it to use the `secondsRequiredToStartPlayingAfterBufferUnderun` or to change `STK_DEFAULT_PACKET_BUFFER_SIZE` (or both)?

**Comment by genzeb** [comment]
Thanks for the excellent library tumtumtum. How much of the audio file is downloaded? I understand what secondsRequiredToStartPlaying and secondsRequiredToStartPlayingAfterBufferUnderun do  but I was wondering if you download just enough to play without interruption or do you buffer the entire file (as you play it)? Thanks.
