### ISSUE TITLE
Switch to play with speaker

### ISSUE THREAD

**Issue by iPermanent** [tumtumtum/StreamingKit#137]
Can you please tell me how can I switch the voice play with Speaker and switch back to the listener? Thanks

**Comment by hyd00** [comment]
I want to switch between earpiece and loud speaker depending on Proximity State, and tried this, but it's not working. The audio always comes from loud speaker, no matter what proximity state is. I believe StreamingKit doesn't use AVAudioSession? Any idea @tumtumtum @iPermanent

**Comment by hyd00** [comment]
Hey so sorry for the confusion.. I missed the setting category part.. It works now 👍 Thanks a lot!
