### ISSUE TITLE
libopus

### ISSUE THREAD

**Issue by secretfader** [tumtumtum/StreamingKit#170]
Provided that I can compile libopus for iOS, is there a way to add additional supported codecs to StreamingKit?

**Comment by richardlevy** [comment]
I'd be interested in this too.  Decoder libraries for Opus, Vorbis and FLAC are available and it would be great to get this into StreamingKit

**Comment by docterd** [comment]
+1. Some more formats like FLAC and Opus would be great.

**Comment by syrakozz** [comment]
+1

**Comment by reejosamuel** [comment]
+ 1

**Comment by patrickjquinn** [comment]
I've said this a few times now. tumtumtum hasn't been active of late. We need a solid fork of the project to get development going again.

**Comment by DrakeWitt** [comment]
+1

**Comment by namitoktalk** [comment]
+1

**Comment by xemacobra** [comment]
+1

**Comment by derpoliuk** [comment]
Guys, if you think that libopus will be helpful to StreamingKit, please contribute to the project, add support and create PR. And I'll do my best to merge it to the project.

@patrickjquinn 

> I've said this a few times now. tumtumtum hasn't been active of late. We need a solid fork of the project to get development going again.

I reached out to @tumtumtum and he added me as a collaborator. I don't have much free time to spend on `StreamingKit`, but I'm using it in my main project and I'll be merging PRs and checking issues from time to time.
