### ISSUE TITLE
Playing an alrealdy queued item shouldn't clear the entire current queue

### ISSUE THREAD

**Issue by diogobalseiro** [tumtumtum/StreamingKit#176]
Hi

Based on what the wiki says and what i've experienced, the only to take advantage of buffering is to allow a item to complete playing and let the player play the next automatically. Is this correct?

Is there no way to skip to the next item in the queue? Right now, the only way to forcefully play the next item is to call play: or setDataSource:, flushing the entire queue and its already buffered items.

**Comment by syrakozz** [comment]
+1

**Comment by wilzh40** [comment]
+1 , this is a great idea I'm struggling with

**Comment by 9mm** [comment]
Also struggling with this
