### ISSUE TITLE
How to intercept audio data and display it visually?

### ISSUE THREAD

**Issue by wilzh40** [tumtumtum/StreamingKit#198]
Hi,

First off, I'd love to thank tumtumtum for his hard work for this project. My question: what I want to accomplish is to take the lower frequencies, find the "beats" of the song, and sync those beats to some visual transformation/indicator to have it "pulse" with the song. Could you guys give me any pointers on how to accomplish this? 

Thanks,
Wilson

**Comment by shuijinliuxi** [comment]
Enable the meteringEnabled property and get 
[_stkPlayer averagePowerInDecibelsForChannel:i]; or  peakPowerInDecibelsForChannel

**Comment by RustamKhisamov** [comment]
I used this:
`for (int i = 0; i < _stkPlayer.frameFilters.count; i++) {
         [_stkPlayer averagePowerInDecibelsForChannel:i];
        }`

**Comment by sandeeprana011** [comment]
```
audioPlayer.appendFrameFilter(withName: "MyCustomFilter") { (channelsPerFrame, bytesPerFrame, frameCount, pointerFrames) in
// Do your computation here
 }
```

**Comment by tumtumtum** [comment]
Like others have pointed out, `averagePowerInDecibelsForChannel` is decent for simple visualizations. If you want to show a visualization for only lower frequencies you'd have to use a custom filter with a FFT (https://developer.apple.com/library/archive/documentation/Performance/Conceptual/vDSP_Programming_Guide/UsingFourierTransforms/UsingFourierTransforms.html).

If someone could provide a sample app or code that would be great.

**Comment by diegostamigni** [comment]
Closing this issue.
