### ISSUE TITLE
How to visualize the music with StreamingKit?

### ISSUE THREAD

**Issue by shuijinliuxi** [tumtumtum/StreamingKit#204]
Is there a way to set setMeteringEnabled and get averagePowerForChannel with StreamingKit just like AVAudioPlayer?

**Comment by sandeepo2o** [comment]
audioPlayer.meteringEnabled = false;
let averagePower = audioPlayer.averagePowerInDecibels(forChannel: CHANNEL_NUMBER);

**Comment by sandeeprana011** [comment]
audioPlayer.meteringEnabled = false;
audioPlayer.averagePowerInDecibels(forChannel: CHANNEL_NUMBER)

**Comment by diegostamigni** [comment]
@shuijinliuxi closing this issue.
