### ISSUE TITLE
Can we reuse a datasource ?

### ISSUE THREAD

**Issue by Centaur** [tumtumtum/StreamingKit#212]
After reading the source code , I found that a STKDataSource is dispose as soon as `dataSourceEof` happens.  So after current audio finished playing if I want to allow user to play the audio again I will have to enqueue another datasource with the same url. Is this observation correct or did I miss something important that a datasource can be reused ?

**Comment by derpoliuk** [comment]
Here's how I do it:

1. Store `STKDataSource` as property to keep strong link and prevent data source from dealloc
2. When user taps play, I call `player.play(dataSource)`(in Swift)

**Comment by derpoliuk** [comment]
@Centaur please close this issue if my answer solves your problem.

**Comment by Centaur** [comment]
@derpoliuk Thank you for the reply. However I cannot verify that it works or not. It has been a long time and I have removed StreamingKit from my dependencies.

**Comment by renatosc** [comment]
After a couple hours trying to make it work, I found out that I needed to have the ARC  ("Objective-C Automatic Reference Counting" set to "YES") enabled on the "Build Settings" tab of my target.
