### ISSUE TITLE
Use of unresolved identifier 'STKAudioPlayer'

### ISSUE THREAD

**Issue by jamesfzhang** [tumtumtum/StreamingKit#229]
I installed StreamingKit using Cocoapod and created a bridge file.

```
#import "RCTBridgeModule.h"
#import <StreamingKit/STKAudioPlayer.h>
```

But I can't use `STKAudioPlayer` in my Swift class. Any ideas?

**Comment by holmesal** [comment]
Did you forget to `import StreamingKit` at the top of your Swift file? 

[like so](https://github.com/stetro/domradio-ios/blob/master/domradio-ios/Controller/PlayerViewController.swift)

**Comment by jamesfzhang** [comment]
Changing it to `#import "STKAudioPlayer.h"` fixed the problem.
