### ISSUE TITLE
Crash when playing a url at STKAudioPlayer.m

### ISSUE THREAD

**Issue by chaoxn** [tumtumtum/StreamingKit#251]
After init, I just play a url and nothing to do. finally crashed at

`status = AudioConverterNew(asbd, &canonicalAudioStreamBasicDescription, &audioConverterRef);`

about line 2000 at STKAudioPlayer.m.

what's wrong.

**Comment by chaoxn** [comment]
oh, it's because of the Exceptions breakpoint. cancel the breakpoint, it's working

**Comment by MrCaiWH** [comment]
为什么会这样？

**Comment by xKundada** [comment]
oh no!!
