### ISSUE TITLE
How to get currently playing stream

### ISSUE THREAD

**Issue by tobitech** [tumtumtum/StreamingKit#265]
Can anyone give me the logic for me to do this:
I am using Streaming Kit to build an audio streaming ios app in objective-c, i displayed list of songs from a web service with their stream URL. When a user selects a song a music player screen is displayed modally to allow the user to control the stream playback pause, play, previous and next. When I dismiss the modal view the song keep playing, and when I select another song from the list, it starts to play while the previously selected continues to play. How can I do it so that, when another is selected, the previously selected is stopped, and if no new one is selected, and I show my modal view again I should be able to still have control over the currently playing stream.
I need the logic for this in objective-c using the streamingkit

**Comment by Dabuk** [comment]
what functions do you perform when you select the new song? are you initializing everything each time?
maybe multiple audio graphs are created..

**Comment by tobitech** [comment]
Something like that, the music player data is set up in the view did load method

**Comment by hirensamiflabs** [comment]
You can create STKAudioPlayer Objects into the AppDelegates and used for the All ViewController where you need its. Otherwise every time create new instance of the Objects. when ViewController is poped. but instance is not poped.

**Comment by hirensamiflabs** [comment]
You can create STKAudioPlayer Objects into the AppDelegates and used for the All ViewController where you need its. Otherwise every time create new instance of the Objects. when ViewController is poped. but instance is not poped.
