### ISSUE TITLE
STKAudioPlayer showing timeoutTimerTick 0/0 attemptReconnect 0/0

### ISSUE THREAD

**Issue by tobitech** [tumtumtum/StreamingKit#268]
I am building an ios objective-c audio streaming app, while i try to stream mp3 files from an http server i keep getting timeoutTimertick 0/0 attemptReconnect 0/0. the issue is i am retrieving a list of songs from a web service, each song has a url to play. i display the list in a collection view, when a song is selected i pass the url to the STKAudioPlayer play method but the song doesn't play, only this shows in my output window timeoutTimertick 0/0 attemptReconnect 0/0. but if i hard code one of the url strings into the method it plays. What could be wrong? I use the same method to get list of radio stations and all the links played, but isn't for .mp3 urls  [Here is a link to my source code](http://1drv.ms/20WFzpx)

**Comment by tumtumtum** [comment]
Hmm the hard coded URLs work? Are you sure the URL you're padding into playURL is correct? Maybe leading or trailing whitespace etc?

**Comment by tobitech** [comment]
tumtumtum, you are the man, that was the issue, it's now solved thanks man. I love your kit

**Comment by technotest2015** [comment]
I facing the same problem. I am streaming the aac audio from server and it is working fine but once I change the slider to play audio from specific position and the problem starts, and giving the following output on console
timeoutTimerTick 7659080/26358278
attemptReconnect 7659080/26358278
Please help me with this issue...
