### ISSUE TITLE
Unresolved identifer for STKAudioPlayerStateReady and STKAudioPlayerStateStopped in new podfiles

### ISSUE THREAD

**Issue by maurodelazeri** [tumtumtum/StreamingKit#269]
I can use the code bellow only with podfile 0.1.25 after I got a message like **unresolved identifer** to 

STKAudioPlayerStateReady
STKAudioPlayerStateStopped

One of the things I tried to do was put STKAudioPlayer.h in my Bridging Header but also did not work, anyone have any idea of the problem?

![pic](https://cloud.githubusercontent.com/assets/1005120/13199703/2c3e3b8c-d7fa-11e5-8f52-ffb15fc1749a.png)

**Comment by tumtumtum** [comment]
I added support for swift enums. Instead of using `STKAudioPlayerStateReady` try simply using `.Ready`

**Comment by maurodelazeri** [comment]
yes, exactly @tumtumtum 
problem solved
