### ISSUE TITLE
Player stop before the end of track when play m4a or mp3 320kb in local

### ISSUE THREAD

**Issue by v2tmobile** [tumtumtum/StreamingKit#273]
Hi,
Have a issue when play m4a or mp3 320kb in local, the player auto stop before the end of track.
Ex:
Track total time is 04:24, but player is stop at 04:16. It's missing a part of music.
Pls help me resolve this issue. Thank you very much.

**Comment by d1248966459** [comment]
I have a save problem.

**Comment by derpoliuk** [comment]
I have similar issue. mp3 track is 01:34 and player stops somewhere between 01:24 and 01:27 but **only if I called `-[STKAudioPlayer seekToTime:]` before**.

**Comment by derpoliuk** [comment]
@v2tmobile did you fix this issue in your code?

**Comment by v2tmobile** [comment]
@derpoliuk Sorry, I haven't fixed this issue, my project was stopped so I don't research more too.

**Comment by derpoliuk** [comment]
#329 is reverted in #377. Reopening this issue.
