### ISSUE TITLE
Resume after audio interruption

### ISSUE THREAD

**Issue by chamrc** [tumtumtum/StreamingKit#28]
Currently, I'm using the following code but it doesn't seem to work at all.

[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(audioInterruptionNotification:) name:AVAudioSessionInterruptionNotification object:nil];
- (void)audioInterruptionNotification:(NSNotification *) aNotification {
  DLog(@"Interrupt %@", aNotification);
  NSDictionary *dict = [aNotification userInfo];
  NSUInteger typeKey = [[dict objectForKey:@"AVAudioSessionInterruptionTypeKey"] unsignedIntegerValue];
  DLog(@"%d", typeKey == AVAudioSessionInterruptionTypeBegan);
  if (typeKey == AVAudioSessionInterruptionTypeBegan) {
      [_player pause];
  } else {
      [_player resume];
  }
  }

I can see all of the messages printing out in the console but music is not resume for some reason. Is there something that I can do here to fix it? Thanks a lot

**Comment by Zulqarnain-Mustafa** [comment]
Same problem, Music does not resume any solution for this.
