### ISSUE TITLE
Playing audio from Documents directory

### ISSUE THREAD

**Issue by rushiofthedeshpandes** [tumtumtum/StreamingKit#304]
Hi there...StreamingKit did help me a lot while streaming an audio from the server. I could also play a local audio, stored in a resource bundle with my player. However, I have been facing some issues when I try to play audio that I have stored in my app's document directory. Unfortunately, the player neither shows any error nor does it play the audio. Any help regarding the issue would be helpful. Thanks in advance.

**Comment by lxcsjk** [comment]
I am also

**Comment by kristoff2016** [comment]
I faced this issue also

**Comment by derpoliuk** [comment]
@rushiofthedeshpandes, @lxcsjk if this issue is still relevant, how did you try to play audio from Documents directory?

Here's my code to play audio from Documents

``` swift
let documents = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
// Assuming there's a file named audio.mp3 in documents
let path = documents.stringByAppendingPathComponent(path: "audio.mp3")
let url = URL(fileURLWithPath: path)
let dataSource = STKAudioPlayer.dataSource(from: url)
self.player.queue(dataSource, withQueueItemId: SampleQueueId(url: url, andCount: 0))
```

If the issues isn't relevant anymore, please close it.

**Comment by kristoff2016** [comment]
Hello, SampleQueueId  where is it come from ? thanks

**Comment by iDevelopper** [comment]
From the example project, not from the library.

**Comment by kristoff2016** [comment]
@iDevelopper  thanks for your replied! I able to fix and play it now thanks

**Comment by derpoliuk** [comment]
I'm closing this issue. @rushiofthedeshpandes feel free to re-open it if you're facing any problems.

@iDevelopper thank you a lot for being active and helpful in this repo!

**Comment by iDevelopper** [comment]
@derpoliuk , I would like to know if you could merge the PR #179?

**Comment by derpoliuk** [comment]
@iDevelopper sure, have you used it in the project? I didn't test it but I want to make sure that it works and doesn't interfere with support of existing formats.

**Comment by iDevelopper** [comment]
@derpoliuk , yes I have used it in an app: 

http://www.shoutradios.fr/

**Comment by kristoff2016** [comment]
@iDevelopper I have a question did your app sometime play and sometime after finished playing it is stuck not move to next song ?

**Comment by iDevelopper** [comment]
In what kind of application. Remote streaming? Local playing?

**Comment by kristoff2016** [comment]
it is Remote streaming but local it's well playing

**Comment by iDevelopper** [comment]
Some files are not well encoded for streaming, there a lot of issues on this: see #384 at the end.
