### ISSUE TITLE
didFinishPlayingQueueItemId and other delegate methods not firing on iOS10

### ISSUE THREAD

**Issue by patrickjquinn** [tumtumtum/StreamingKit#305]
We are using the delegate methods to start the next track in the background, but as of iOS 10 it seems that those methods aren't being called in the background state anymore. Is the player being Dealloced? It's a static singleton so it shouldn't be but i think iOS10 is handling memory management very differently.

**Comment by alexkendall** [comment]
@patrickjquinn Also having this issue.
