### ISSUE TITLE
Expose SSL settings in STKHTTPDataSource

### ISSUE THREAD

**Issue by kevintulod** [tumtumtum/StreamingKit#309]
I had a bunch of issues with `CFNetwork SSLHandshake failed (-9824)` for certain URLs.

After careful inspection of SSL certs and comparing against ones that work, it seems that my server requires Server Name Indicator (SNI) verification. The SSL settings seem to force a null for `kCFStreamSSLPeerName` (see settings defined at https://github.com/tumtumtum/StreamingKit/blob/master/StreamingKit/StreamingKit/STKHTTPDataSource.m#L556)

Would it be possible to get these SSL settings exposed? My temporary workaround is to remove the null for `kCFStreamSSLPeerName` and compile StreamingKit without using CocoaPods, but it would be much cleaner if I could pass in the preferred SSL settings when instantiating StreamingKit.

**Comment by docterd** [comment]
I'm seeing the same issue here. Would be great to see this exposed.

**Comment by seldomseenkid** [comment]
Same problem here.

**Comment by patrickjquinn** [comment]
@kevintulod Would you be able to share your work around to kCFStreamSSLPeerName here? This driving me batty.

**Comment by kevintulod** [comment]
@patrickjquinn I don't have access to this at this very moment, but will gladly share it when I do. IIRC in the aforementioned file I just removed the reference to the kCFStreamSSLPeerName in the dictionary.

From this:
```  NSDictionary* sslSettings = [NSDictionary dictionaryWithObjectsAndKeys:
(NSString*)kCFStreamSocketSecurityLevelNegotiatedSSL, kCFStreamSSLLevel,
[NSNumber numberWithBool:NO], kCFStreamSSLValidatesCertificateChain,
[NSNull null], kCFStreamSSLPeerName,
nil];
```

To this:
``` NSDictionary* sslSettings = [NSDictionary dictionaryWithObjectsAndKeys:
(NSString*)kCFStreamSocketSecurityLevelNegotiatedSSL, kCFStreamSSLLevel,
[NSNumber numberWithBool:NO], kCFStreamSSLValidatesCertificateChain,
nil];
```

I'll send back an update once I can verify this is correct.

**Comment by seldomseenkid** [comment]
@patrickjquinn I can confirm I made the change @kevintulod describes and it solved the problem for me.
