### ISSUE TITLE
I get STKAudioPlayerErrorAudioSystemError 

### ISSUE THREAD

**Issue by mutongs** [tumtumtum/StreamingKit#311]
The url is "http://pt.qi-zhu.com/@/2016/12/14/b8e3b384-0185-47aa-bc67-3323b0d1156c.aac",
and then I get the STKAudioPlayerErrorAudioSystemError , What's the problem? Please help me,thanks.

**Comment by gnchishti** [comment]
I have the same problem..

did you get any solution?

**Comment by louiszgm** [comment]
I have the same problem.
did anyone solve this out?
