### ISSUE TITLE
Error when streaming audio from S3 file

### ISSUE THREAD

**Issue by ecristerna** [tumtumtum/StreamingKit#318]
I have some audio files on S3 that I need to playback on my iOS app. But for some reason, an error is logged when trying to connect to the URL. Any URL is working just right, but those on S3 are not.

Here is the logging…
<img width="367" alt="screen shot 2017-01-24 at 10 19 25 am" src="https://cloud.githubusercontent.com/assets/3680271/22255912/9e2fe126-e21e-11e6-8f1f-a5efa87f92ce.png">

**Comment by adimnno** [comment]
This #309 might resolve the problem
