### ISSUE TITLE
How we will Calculate BPM of Song ?

### ISSUE THREAD

**Issue by anandmahajan** [tumtumtum/StreamingKit#328]
Hi,

@tumtumtum 

Is there any way to calculate BPM ?

Thanks,
Anand Mahajan

**Comment by patrickjquinn** [comment]
BPM is calculated by looking a the peak power of an audio signal, you should be able to get this from the PCM buffer.

**Comment by anandmahajan** [comment]
Hi 
@patrickjquinn any sample code for get BPM from PCM buffer?

Thanks

**Comment by patrickjquinn** [comment]
There is a sample in the docs as to how you access the PCM buffer, I've never calculated the BPM using StreamingKit on the fly so I cant tell you how to do it but heres a repo that does it for local files https://github.com/yaizudamashii/BPMDetection-iOS
