### ISSUE TITLE
active fork?

### ISSUE THREAD

**Issue by tomj** [tumtumtum/StreamingKit#331]
This is a great project, though there seem to be some niggling issues which can be solved - is there a favoured active fork around?  I've been looking through the network graph but haven't found anything definitive.

Cheers! 😀

**Comment by patrickjquinn** [comment]
I'm in exactly the same boat. Would really like an active fork so I can switch my projects back to this.

**Comment by iDevelopper** [comment]
@tomj , @patrickjquinn , what issues? What do you a fork does?

**Comment by patrickjquinn** [comment]
My biggest issue is https://github.com/tumtumtum/StreamingKit/issues/325 which actually meant I had to build my own AudioPlayer abstraction based on AVPlayer. If that wasnt an issue it would literally be the perfect framework!

**Comment by iDevelopper** [comment]
@tumtumtum still reply for some issues. I wish he will maintain his library as it is the better one in my opinion.

**Comment by doriansgithub** [comment]
Have you guys tried AudioKit?

**Comment by iDevelopper** [comment]
I have to play live stream URL and not file URL, I don't know if AudioKit can do this. I don't think so.

**Comment by patrickjquinn** [comment]
Dont think AudioKit can handle streaming (Correct me if i'm wrong) also its a swift framework and i'm stuck firmly in the dark age of Objective-C with my project :(

**Comment by doriansgithub** [comment]
Got it.

**Comment by iDevelopper** [comment]
i.e ?

**Comment by doriansgithub** [comment]
Just saying that I understand that AudioKit won't work for you... lol
