### ISSUE TITLE
seekToTime not working for some URLs

### ISSUE THREAD

**Issue by anuragdadheech** [tumtumtum/StreamingKit#332]
I am trying to play these two URLs.

http://developer.raydio.in/api/v1/episode/a1c52d4e-b675-4330-a5dd-fcda3c0a381e/serve

http://storage.googleapis.com/storeo-test-bucket/storeo_serve

These 2 URLs have exact same media, both work perfectly fine while streaming. But `seekToTime` doesn't work for first one. I tried to debug and found out that in the function `processSeekToTime`, length of `currentlyPlayingEntry`'s datasource is `0`, hence it's returning from there.

Additionally, another difference is that first one is being served from google cloud platform blobstore. Any help will be appreciated.

**Comment by tomj** [comment]
something to do with the MIME type on the files?  Just now when clicking on them in the browser the Google one attempts to download while the `raydio.in` link streams - is there any reason they're not audio file types like MP3 etc? 😄

**Comment by lvialle** [comment]
this is probably because the server does not have in their http headers the Accept-Ranges key
