### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by iDevelopper** [tumtumtum/StreamingKit#338]
CPU usage is very high with this great library. 12-15% before play anything. And 20-25% while streaming http url. Why?

**Comment by patrickjquinn** [comment]
For me its 1-2%, have you profiled your app in instruments to verify its STK causing the spike?

**Comment by iDevelopper** [comment]
It was with your example. After integration of your library in my project: (but I play some live stream url over http):

Then, not so bad??...

And this pourcentage increase when I request for an artwork image using iTunes API, display it etc..., but normal...

![2017-05-10_15-40-07](https://cloud.githubusercontent.com/assets/1782450/25901620/95429fdc-3597-11e7-91d8-c42687c79ffb.png)

**Comment by iDevelopper** [comment]
There is a difference (for memory) between Xcode and Instrument:

![2017-05-10_16-02-43](https://cloud.githubusercontent.com/assets/1782450/25902649/737e8908-359a-11e7-806b-9330072a5d9c.png)
