### ISSUE TITLE
Interruptions handle

### ISSUE THREAD

**Issue by iDevelopper** [tumtumtum/StreamingKit#339]
When I activate my audio session, I add an observer for AVAudioSessionInterruptionNotification. However, my handle method is called for AVAudioSessionInterruptionTypeBegan but never for AVAudioSessionInterruptionTypeEnded. And the application do not resume audio after interruption. Any ideas about this? Thanks.

**Comment by doriansgithub** [comment]
Did you get the EQ to actually work?  I couldn't get it to work.

**Comment by iDevelopper** [comment]
Yes it works. See #337 and @tumtumtum explanation.
