### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by iDevelopper** [tumtumtum/StreamingKit#340]
Hi,

What about deprecated functions and variables?

CFReadStreamCreateForHTTPRequest

kCFStreamPropertyHTTPResponseHeader
kCFStreamPropertyHTTPShouldAutoredirect
kCFStreamPropertyHTTPProxy

Is this great library will continue to be maintained?

**Comment by patrickjquinn** [comment]
Looking at the commit logs I think we have our answer!! Here's hoping https://github.com/tumtumtum/StreamingKit/issues/325 gets addressed! (Looking forward to switching my project back to STK)

**Comment by iDevelopper** [comment]
Yes I saw. This is very promising!

**Comment by diegostamigni** [comment]
I'm getting rid of some deprecated stuff. Unfortunately, some of those (the ones around CFNetwork) require a rewrite of the HTTP data source. I'll look into that.
