### ISSUE TITLE
Set number of bands error

### ISSUE THREAD

**Issue by iDevelopper** [tumtumtum/StreamingKit#341]
Hi,

If a create an instance of STKAudiPlayer with bands 20, 28, 40, 57, 80, 113, 160, 226, 320, 453, 640, 905, 1280, 1810, 2560, 3620, 5120, 7241, 10240, 14482, 20408, 0

I get an error -10851 here:

```
	CHECK_STATUS_AND_RETURN(AudioUnitSetProperty(eqUnit, kAUNBandEQProperty_NumberOfBands, kAudioUnitScope_Global, 0, &eqBandCount, sizeof(eqBandCount)));
```

If I create it with 20, 40, 80, 160, 320, 640, 1280, 2560, 5120, 10240, 20480, 0, it is Ok, why ?

I would like to have more than 11 bands.

Thanks

**Comment by tumtumtum** [comment]
There's a limit of 16 bands on iOS unfortunately.

**Comment by iDevelopper** [comment]
Thanks for the response.

I just tested and you are right. But it seems this is a default value for kAUNBandEQProperty_MaxNumberOfBands parameter which can be modified.

You could add (I tested and no more error with a number of bands > 16):

```
    CHECK_STATUS_AND_RETURN(AudioUnitSetProperty(eqUnit, kAUNBandEQProperty_MaxNumberOfBands, kAudioUnitScope_Global, 0, &eqBandCount, sizeof(eqBandCount))); // Or 24 as it is the size of equalizerBandFrequencies
```

Thanks again!
