### ISSUE TITLE
Don't support 'Transfer-Encoding'

### ISSUE THREAD

**Issue by GongTengFei** [tumtumtum/StreamingKit#342]
When httpheaders dont't have a 'content-length' key, i can't get the audio duration. For example, "Transfer-Encoding" = Identity; "Transfer-Encoding" = chunked;

**Comment by patrickjquinn** [comment]
Can you give us a sample data stream that causes this behavior?

**Comment by GongTengFei** [comment]
http://220.181.190.187/tellingVnum/callmanage/records/1000004_635ad5b44e01be14_18200389572_17072881437_13982136183.mp3

**Comment by GongTengFei** [comment]
I sovle this problem by set a "requestHeaders" field with @{
                             @"Accept-Encoding": @"gzip"
                             }

**Comment by patrickjquinn** [comment]
I feel like this could possibly solve our M4A issue.... would you mind posting the code for this change? Either as a snippet here or as a PR?

Certainly a worthwhile improvement!

**Comment by GongTengFei** [comment]
![image](https://user-images.githubusercontent.com/11581582/39744524-256d6652-52d7-11e8-91cc-ce65be32eef8.png)
