### ISSUE TITLE
Won't play songs over 6 minutes.

### ISSUE THREAD

**Issue by doriansgithub** [tumtumtum/StreamingKit#345]
Is this a known issue?  Am I to change the default settings?

**Comment by iDevelopper** [comment]
I don't understand. You wrote in an other issue #337 you play songs from iTunes Library. Then you probably use AVAudioPlayer. StreamingKit can't play songs from iTunes Library. Can you elaborate what are you doing?

**Comment by doriansgithub** [comment]
We are playing song from our iPhones internal storage.  I believed that's the iTunes library.  I mean, it's the exact same songs that are loaded into the Music Player synchronized via iTunes.

We create a array from the songs and feed it as an NSURL to streaming kit.

It works except the EQ and the 5:30 song issue.  But the gapless is working flawless now.

**Comment by doriansgithub** [comment]
Here is what we are feeding StreamKit.

-(void) audioPlayer:(STKAudioPlayer*)audioPlayer didFinishBufferingSourceWithQueueItemId:(NSObject*)queueItemId {

    QueueID* queueId = (QueueID*)queueItemId;
    
    MPMediaItem *item =
    [MediaPlayerNavigation nextSongFromArray:UniversallyPlayer.defaultPlayer.arrSongs
                                     isQueue:YES];
    
    [MediaPlayerNavigation fillSongInfo:item];

    NSURL *url = [item valueForProperty:MPMediaItemPropertyAssetURL];

    [self queueDataSource:[STKAudioPlayer dataSourceFromURL:url]
          withQueueItemId:[[QueueID alloc] initWithUrl:queueId.url andCount:queueId.count + 0]];
}

**Comment by iDevelopper** [comment]
Then you play songs from file URL. Did you have a look to the sample I wrote in #337? For EQ?

**Comment by doriansgithub** [comment]
Yes, absolutely, and I just saw and replied to your message with the sample.  I'm going to try the EQ right now, but I really need to figure out why it's not playing large songs.

**Comment by iDevelopper** [comment]
I have no problem with large songs. You can replace the song in the sample with an other song more large...

**Comment by doriansgithub** [comment]
Good idea, I'll try that.

**Comment by doriansgithub** [comment]
I looked at the sample and still crash.  I'm wondering, does the EQ have to be part of the main view controller?  Because in our app, the EQ is it's own view controller with it's own xib and the player is it's own separate files.  We have this same type of set up with Novocaine and the EQ works.

**Comment by doriansgithub** [comment]
I can't substitute BrainDamage with any other song.  It crashes.  I change it back to BrainDamage and it works fine.

**Comment by iDevelopper** [comment]
My sample crash? Or your app?

**Comment by doriansgithub** [comment]
Your sample.  I put in 3 different songs, no spaces in the names, all from cds m4a, lossless.  Same exact location as the BrainDamage song.  Dragged into the project, and checked copy.  Changed the name in the view controller.m.

**Comment by iDevelopper** [comment]
Did you check after dragging your song that the target is checked. The song file must be in the bundle. Go to the build phase tab and be sure that your song file is present in the copy bundle:

![2017-05-22_08-36-13](https://cloud.githubusercontent.com/assets/1782450/26295381/de242c26-3ec9-11e7-80cc-3c73352a98a5.png)

**Comment by iDevelopper** [comment]
Here is the modified sample, with a longer song (Time, 6mn53) and the eq in a separate view.

[STKSample.zip](https://github.com/tumtumtum/StreamingKit/files/1017957/STKSample.zip)

**Comment by doriansgithub** [comment]
Ok, I'll check tomorrow.  Thanks!!

**Comment by doriansgithub** [comment]
I did, and it doesn’t crash, but doesn’t play either.  Look at the constant error No. 4 stream.

**Comment by doriansgithub** [comment]
We are checking out your new sample, which is much closer to what we are doing.

Again, THANK YOU!!!!

**Comment by doriansgithub** [comment]
Dude, we got it to work!!!!  I’m going ballistic!!!! I”m going to have a shot of vodka in the middle of a monday!!!!

You the man!!!

**Comment by iDevelopper** [comment]
Great!

**Comment by iDevelopper** [comment]
What was the probeme?

**Comment by doriansgithub** [comment]
The way we were setting the new player.

1st My Low Level programmer wasn't setting this right:

@implementation StreamingPlayer

- (instancetype)init {

if (self) {
        [self stop];
        self = nil;
    }

and this:

self = [[StreamingPlayer alloc] initWithOptions:(STKAudioPlayerOptions)

This combo made it impossible for it to reinit properly.

We are going to release it and we are going to state that the EQ is Powered by StreamKit.

I'll get you complementary IAP for the app.

**Comment by doriansgithub** [comment]
You guys should set up a contribution bank. I'll contribute immediately.

**Comment by doriansgithub** [comment]
We had it like this:

   self = [super initWithOptions:(STKAudioPlayerOptions) {

Instead of like this:

self = [[StreamingPlayer alloc] initWithOptions:(STKAudioPlayerOptions) {

**Comment by doriansgithub** [comment]
The super just wasn't finding it's way thru the haze.
