### ISSUE TITLE
State gets changed to buffering and nothing happens.

### ISSUE THREAD

**Issue by daria-kopaliani** [tumtumtum/StreamingKit#349]
State gets changed to buffering and nothing happens. Shouldn't there be a timeout?

**Comment by patrickjquinn** [comment]
There is a timeout delegate method I  believe...are you listening for it?

**Comment by daria-kopaliani** [comment]
It turns out the reason lies in `STKAutoRecoveringHTTPDataSource` calling `processRetryOnError` method no matter what the status code is. Files I stream are huge (a few hours of playback) and sometimes the URL gets expired (a `410` error code) or in case of extensive seeking I might get a `429` error (the number of requests exceeded the limit). In these cases the streaming URL is no longer valid, but `STKAutoRecoveringHTTPDataSource` stills tries to reconnect and never succeeds or notifies a delegate (`STKAudioPlayer`) of these errors which results in endless buffering. I ended up making a fork and handle `410` & `429` errors there, but may be `STKAudioPlayer ` should get notified of them in the main brunch.

**Comment by diegostamigni** [comment]
Closing this issue
