### ISSUE TITLE
This a memory issue!!!

### ISSUE THREAD

**Issue by wendongsheng** [tumtumtum/StreamingKit#350]
When i want to dealloc STKAudioPlayer, i call the methods:
[_bgPlayer stop];
[_bgPlayer dispose];
_bgPlayer = nil;
if the everything is ok, the player dealloc method need called ,but it is crash:

if (newState != previousState && !deallocating)
    {
        self.state = newState;
        
        OSSpinLockUnlock(&internalStateLock);
        
        dispatch_async(dispatch_get_main_queue(), ^
        {
            [self.delegate audioPlayer:self stateChanged:self.state previousState:previousState];
        });
    }
Thread 1:EXC_BAD_ACCESS(code=EXC_i386_GPFLT):[self.delegate audioPlayer:self stateChanged:self.state previousState:previousState];
i am is crash too......

**Comment by derpoliuk** [comment]
A lot of users of the app I'm working on are having this issue. This crash happen on iOS 9, 10 and 11. This line crashes: https://github.com/tumtumtum/StreamingKit/blob/master/StreamingKit/StreamingKit/STKAudioPlayer.m#L475
