### ISSUE TITLE
How to up the rate speed ?

### ISSUE THREAD

**Issue by kinhkyo** [tumtumtum/StreamingKit#351]
During play audio, I want to up speed rate how can I do that?

**Comment by iDevelopper** [comment]
I think you can't.

**Comment by newbdez33** [comment]
try this pull request:
https://github.com/tumtumtum/StreamingKit/pull/262

**Comment by kinhkyo** [comment]
@newbdez33 Thank you very much. I got it :)

**Comment by diegostamigni** [comment]
Closed as it is a solved issue.
