### ISSUE TITLE
How to set rate?

### ISSUE THREAD

**Issue by MillerJiang538** [tumtumtum/StreamingKit#355]

**Comment by patrickjquinn** [comment]
Hi @MillerJiang538 try and leave a proper description of your problem, what you've tried and where your research has gotten you when reporting an issue. The repository author nor the community will help you otherwise.

**Comment by MillerJiang538** [comment]
@patrickjquinn like as AVAudioPlayer @property float rate NS_AVAILABLE(10_8, 5_0); /* See enableRate. The playback rate for the sound. 1.0 is normal, 0.5 is half speed, 2.0 is double speed. */ .
I wan't change play rate  when audio play online.Thanks!

**Comment by iDevelopper** [comment]
Do you mean rate for speed? Not for sound... I think you can't as there is not property for that in this library!

**Comment by dong136279559** [comment]
I also need this rate attribute. Could the author update the library and add this attribute,please!!!!!!,thank you

**Comment by diegostamigni** [comment]
As mentioned in other (similar) issues, it isn't the responsibility of this library to expose these functionalities but rather in a top level player.
