### ISSUE TITLE
Play Locally Song not Play

### ISSUE THREAD

**Issue by Swastiksaraf** [tumtumtum/StreamingKit#359]
I want to play apple music audio.They not play . Please help .
Here is my locally path.
file:///private/var/mobile/Containers/Data/Application/F0322196-7515-43CF-B1B2-D7C3D9F16B6A/tmp/0B0ACA97-77B7-4BCF-BB34-90DAD5D6A961.m4a

  audioPlayer = STKAudioPlayer()
   
        audioPlayer?.resume()
        
        let dahlen = STKAudioPlayer.dataSource(from: myURl!)
        audioPlayer?.setDataSource(dahlen, withQueueItemId: dahlen)

**Comment by Swastiksaraf** [comment]
Please hep it is my job issue.

**Comment by doriansgithub** [comment]
Apple Music?  Do you have an Apple Music account?  Unless the user is authenticated, they won't play. i believe you can set them up for 30 seconds if you set them up right.

**Comment by JacobSyndeo** [comment]
This isn't for playing Apple Music—it's for playing audio files either stored locally within your app bundle, or from remote URLs.
What you're looking for is [MusicKit](https://developer.apple.com/musickit/)

**Comment by JacobSyndeo** [comment]
This isn't for playing Apple Music—it's for playing audio files either stored locally within your app bundle, or from remote URLs.
What you're looking for is [MusicKit](https://developer.apple.com/musickit/).

**Comment by doriansgithub** [comment]
You can play local songs that where purchased from iTunes, but you can't play songs from Apple Music.
