### ISSUE TITLE
ExampleApp - "linker command failed with exit code 1"

### ISSUE THREAD

**Issue by mitchdowney** [tumtumtum/StreamingKit#361]
I'm trying to start the ExampleApp to play around, but immediately when I try building I get a "linker command failed with exit code 1" issue.

Is this a bug with the ExampleApp? If not, any tips on what I need to do to fix this?

![image](https://user-images.githubusercontent.com/2262919/29345819-da433bbc-8206-11e7-9827-11f5dd5818ec.png)

**Comment by iDevelopper** [comment]
Open StreamingKit.xcworkspace instead of ExampleApp.xcodeproj to have the library in your project.

**Comment by mitchdowney** [comment]
Whoops! 🤦‍️ Thanks!
