### ISSUE TITLE
Can we stop buffering after a specified time or byte range with StreamingKit?

### ISSUE THREAD

**Issue by mitchdowney** [tumtumtum/StreamingKit#362]
Use case: I want to stream and buffer only 3 minutes of a 2 hour mp3 remotely hosted on someone else's server, and their server supports byte range requests. I do not want to waste bandwidth downloading data before or after that 3 minute range (or at least, I want to minimize how much is downloaded before/after that range).

Is this something we can achieve with StreamingKit?

I see we can set a value for the bufferSizeInSeconds. Maybe that for the most part accomplishs what I'm looking for?

**Comment by mitchdowney** [comment]
Based on watching the network tab in the debugger menu, it looks like StreamingKit buffers only 10 seconds at a time or so at a time. Am I interpreting this correctly? 

So if I stream and play 3 minutes of a 2 hour mp3 file with StreamingKit, I should only download about 3 minutes and 10 seconds worth of data for that file?

**Comment by patrickjquinn** [comment]
Look in the sample iOS app, you’ll see a property in the STK initialization for bufferTimeInSeconds (it’s also in the header), modify that for your target duration.

**Comment by mitchdowney** [comment]
Thanks! I spent weeks trying to roll this feature myself. So glad StreamingKit does this by default 😅
