### ISSUE TITLE
iOS11 (beta) cannot seek in local file

### ISSUE THREAD

**Issue by audioforge** [tumtumtum/StreamingKit#364]
When running the demo project on beta7 of iOS11 and playing a local file and trying to seek to a random position, the playback stops and the console spits out a lot of comments like:
AACDecoder.cpp:220:DecodeFrame:  Error deserializing packet
Is this a beta issue or StreamingKit?
This is not an issue in iOS10 so I would suspect iOS11 being the culprit. Or did Apple change a fundamental piece in the puzzle that StreamingKit is relying on?

**Comment by derpoliuk** [comment]
@audioforge I didn't run `StreaminKit`'s demo app for a while but `StreamingKit` is working in live app with local audio files.

Is this issue still relevant?

**Comment by audioforge** [comment]
I’ll check it again over the weekend. Cheers!

Kind regards,
Tibor

Tibor Horvath | Audioforge Labs Inc. | www.audioforge.ca

**Comment by audioforge** [comment]
This is issue have been resolved (probably by iOS11 itself).

Thanks!
T

Tibor Horvath | Audioforge Labs Inc. | www.audioforge.ca

**Comment by derpoliuk** [comment]
@audioforge thank you for taking time and checking this issue!

_Closing..._
