### ISSUE TITLE
Can we load a file in the player without having it play immediately?

### ISSUE THREAD

**Issue by mitchdowney** [tumtumtum/StreamingKit#367]
I'd like to load a file in the audioPlayer so that I can determine the duration of the file and populate the UI with the duration, but I don't want the file to begin playback immediately. 

Is it possible to load a file in the player but not play it immediately with StreamingKit?

**Comment by iDevelopper** [comment]
You don't need to load the file to know the duration:

```
    AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
    int duration = CMTimeGetSeconds(asset.duration);
    _durationLabel.text = [NSString stringWithFormat:@"%02d min %02d sec", duration / 60, duration % 60];
```

**Comment by mitchdowney** [comment]
Ok great! It'd be nice if I could load a media file into the StreamingKit audioPlayer without it automatically playing, but if that's not possible this workaround you've provided works for my use case. Thanks :)
