### ISSUE TITLE
STKAudioPlayer get remote audio duration wrong

### ISSUE THREAD

**Issue by sauchye** [tumtumtum/StreamingKit#368]
Hi, thanks great open. when i use StreamingKit, i use ``NSTimer`` get audio ``duration``, but gain wrong ,eg 

http://testpic.yxxy.tv/audio/1504688560.mp3

here my code https://github.com/sauchye/StreamingKitDemo

```
- (void)startTimer{
    if (!_timer) {
        _timer = [NSTimer scheduledTimerWithTimeInterval:1 target:self selector:@selector(tick) userInfo:nil repeats:YES];
        [[NSRunLoop currentRunLoop] addTimer:_timer forMode:NSRunLoopCommonModes];
    }
}

- (void)tick{
    
    float progress = self.audioPlayer.progress;
    float duration = self.audioPlayer.duration;
    self.durationLabel.text = [NSString stringWithFormat:@"%.2f", duration];
    NSLog(@"=====duration=====\n%.f", duration);
    NSLog(@"=====progress=====\n%.f", progress);
}



```

<img width="388" alt="screenshot" src="https://user-images.githubusercontent.com/4171847/30509355-56b4c1aa-9ae1-11e7-84b0-083d852b82d7.png">

**Comment by veila** [comment]
same issue with large files as flac or m4a

**Comment by veila** [comment]
use
 AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
    int duration = CMTimeGetSeconds(asset.duration);
to get duration. It works for me

**Comment by sauchye** [comment]
@veila thank you
