### ISSUE TITLE
Cannot play the audio in background - iOS 11 - using it in SWIFT

### ISSUE THREAD

**Issue by deeprathod** [tumtumtum/StreamingKit#372]
Hello team, 

First of all thank you for making an awesome library. Appreciate all the team. I am using this library in one of the application, where as soon as the device got updated to iOS 11, it stopped playing the audio in the background and also not showing in controlcenter.

Did anybody faced such issue ?

Thanks In Advance.

**Comment by doriansgithub** [comment]
No, but when we open some views, the audio plays without the user pressing play.  So I guess it's backwards to what you are experiencing.

**Comment by patrickjquinn** [comment]
If you haven’t already, move your player and player related logic to a singleton. IOS 11 has changed the lifecycle Of Views.

**Comment by doriansgithub** [comment]
Oh, got it!  Thanks!!

**Comment by deeprathod** [comment]
Hello, The music player which my app has doesn't play at all in the background. It doesn't even show in the controlcenter i am using this library.

**Comment by patrickjquinn** [comment]
This library isn’t a magic bullet that makes background audio and control centre work.

For background audio, in Xcode go to the capabilities -> background mode -> [check] Audio, AirPlay, and Picture in Picture.

For control centre research mpnowplayinginfocenter https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter

and once again, if you've not already done so, move your player to a singleton pattern.

**Comment by rathod24** [comment]
Even example app doesn't play music in background on iOS11

**Comment by patrickjquinn** [comment]
@rathod24 did you not see my comment about using the singleton pattern under iOS 11?

**Comment by iDevelopper** [comment]
Absolutely NO need to use a singleton pattern!

**Comment by rathod24** [comment]
What should i do for stream in background then? i've declared STKAudioPlayer variable in AppDelegate and using in whole app. and it's initialising once only

**Comment by iDevelopper** [comment]
And YES, the StreamingKit sample play in background mode on iOS 11!

**Comment by deeprathod** [comment]
@iDevelopper  I just checked with the StreamingKit Sample, its not getting played in the background of iOS 11. :( :(

**Comment by iDevelopper** [comment]
@rathod24 , I just checked to! It works in background on iOS 11! Perhaps you tested on simulator. You have to test on a real device.

**Comment by deeprathod** [comment]
Wooooo hoooo Thanks @iDevelopper  :) You made my day. its working on the device. Thanks.
