### ISSUE TITLE
Not able to stream my aac track.

### ISSUE THREAD

**Issue by davinder2292** [tumtumtum/StreamingKit#373]
When i am trying to stream my aac file then i am getting following error.
`ACMP4BitStreams.cpp:565:ParseESDSBitStream:  ACMP4BitStreams::ParseESDSBitStream: the ES_Descriptor tag is incorrect`
`2124:  AudioCodecInitialize failed`
`dataSourceEof`

**Comment by patrickjquinn** [comment]
Can you give us a sample stream of the AAC url that is causing this error?

**Comment by diegostamigni** [comment]
Closing this issue as no feedback given.
