### ISSUE TITLE
What's the correct way to deinit the player in Swift?

### ISSUE THREAD

**Issue by hao44le** [tumtumtum/StreamingKit#378]
`
self.audioPlayer is a type of STKAudioPlayer`

Below is my code for deinit

`
self.audioPlayer?.stop()
self.audioPlayer?.clearQueue()
self.audioPlayer?.dispose()
self.audioPlayer?.delegate = Constant.dummySTKAudioPlayer
self.audioPlayer = nil
`

But when I profile my app with Leak instrument, I can see couple MB of memory leak on STKAudioPlayer init when my app enters the play viewcontroller again.
So, what's the correct way of deinit all STKAudioPlayer stuff?

Thanks

**Comment by haritowa** [comment]
If you have metering enabled, leak may be caused by a bug: https://github.com/tumtumtum/StreamingKit/pull/391

Otherwise, dispose and remove all strong references should work

**Comment by diegostamigni** [comment]
Closing as no more feedback given.
