### ISSUE TITLE
Can't stop music from playing at start up.

### ISSUE THREAD

**Issue by doriansgithub** [tumtumtum/StreamingKit#379]
Music Plays at app start up and even when app is not running... I've tried everything.  Anyone else experiencing this or with a solution?

**Comment by iDevelopper** [comment]
If you don't want music to play when app is not running in foreground, deselect audio background mode in the tab capabilities.

**Comment by doriansgithub** [comment]
I do want music while app is in background.  The issue is that music plays even when the app is literally not running, and at start up, which Apple will not allow. The user needs to hit play for music to play.  But the song starts all on its own.

**Comment by iDevelopper** [comment]
I do not have these issues. Could you download my application to check the behaviour and tell me if it is your requirement? I submitted it this month. After I will be able to share some part of code.

http://shoutradios.fr/

**Comment by doriansgithub** [comment]
Nice app!  But it doesn’t load a song at start up, so there is no way to know if it would start up on it’s own.  Our app loads a song at start up so that the info view is not empty.  Prior to the changes Apple has implemented, it would load the song, and we would simply pause at start up.  But now the pause is completely ignored as StreamKit loads another song after the first pause and subsequently starts playing it.  

At this time, I’ve put a timer for 3 seconds after start up with a pause.  But it’s really not a very elegant solution because start up times vary, and it could miss the 3 seconds and play a song. If that happens while at the Apple Review process, we’d be rejected.  

But worst is the fact that it can start a song out of nowhere all on it’s own even when our app is not even running.  It’s like a ghost in the machine.  I now put a stop when quitting, and haven’t head another song play on it’s own.  But we never needed that before.  Once the app used to quit, the music would stop and that would be it, no songs ever played without the player running one way or another.

We’ll keep looking into this.

**Comment by iDevelopper** [comment]
And what about UIApplicationDidBecomeActiveNotification?

```
- (void)pause {
    [_audioPlayer pause];
    [_playPauseButton setImage:[UIImage imageNamed:@"Play"] forState:UIControlStateNormal];
}

- (void)didBecomeActive:(id)sender {
    NSLog(@"didBecomeActive state: %@", [self stringFromState:_audioPlayer.state]);
    if (_audioPlayer.state != STKAudioPlayerStatePlaying) {
        [self pause];
    }
}

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(didBecomeActive:)
                                                 name:UIApplicationDidBecomeActiveNotification
                                               object:nil];
    ...
```

Example:

[STKSample-2.zip](https://github.com/tumtumtum/StreamingKit/files/1484418/STKSample-2.zip)

**Comment by doriansgithub** [comment]
Well it looks like you hit the nail on the head!  We were calling for a pause but only locally, so the system was only aware of it AFTER we paused.  The pause had to be handled by the delegate not us. 

Thank you!!

**Comment by doriansgithub** [comment]
Sorry to bother again, but I have another odd issue.

If I’m playing thru an Apple TV, and a song ends, the next song plays perfectly, but if I force the next song by hitting next, I can see the song playing because the artwork is visible and the visualizer is firing, but the Apple TV doesn’t sound.

Any clues? It might be something we are doing, but just want to make sure you haven’t seen this issue.

**Comment by iDevelopper** [comment]
Hello, what is your code when you hit the next button?

**Comment by doriansgithub** [comment]
Will do.

Do you use this?

    if (@available(iOS 11.0, *)) {
        [MPNowPlayingInfoCenter defaultCenter].playbackState = MPNowPlayingPlaybackStatePlaying;
    } else {
        // Fallback on earlier versions
    }

**Comment by iDevelopper** [comment]
No, I use:

```
- (void)activateAudioSession
{
    NSError *error = nil;
    self.audioSession = [AVAudioSession sharedInstance];
    
    [_audioSession setCategory:AVAudioSessionCategoryPlayback error:&error];
    [_audioSession setPreferredSampleRate:44100.0 error:&error];
    [_audioSession setPreferredIOBufferDuration:0.1 error:&error];
    if (error) {
        [_appDelegate showAppErrorWithTitle:JMOLocalizedString(@"Error", @"") andMessage:error.localizedDescription];
    }
    else {
        BOOL success = [_audioSession setActive:YES error: &error];
        if (!success && error) {
            [_appDelegate showAppErrorWithTitle:JMOLocalizedString(@"Error", @"") andMessage:error.localizedDescription];
        }
        else {
            NSNotificationCenter *nc = [NSNotificationCenter defaultCenter];
            [nc addObserver:self selector:@selector(handleRouteChanged:) name:AVAudioSessionRouteChangeNotification object:nil];
            [nc addObserver:self selector:@selector(handleInterruptions:) name:AVAudioSessionInterruptionNotification object:nil];
        }
    }
    [MPRemoteCommandCenter sharedCommandCenter].playCommand.enabled = YES;
    [[MPRemoteCommandCenter sharedCommandCenter].playCommand addTarget:self action:@selector(play)];
    
    [MPRemoteCommandCenter sharedCommandCenter].pauseCommand.enabled = YES;
    [[MPRemoteCommandCenter sharedCommandCenter].pauseCommand addTarget:self action:@selector(pause)];
    
    [MPRemoteCommandCenter sharedCommandCenter].previousTrackCommand.enabled = YES;
    [[MPRemoteCommandCenter sharedCommandCenter].previousTrackCommand addTarget:self action:@selector(rewind:)];
    
    [MPRemoteCommandCenter sharedCommandCenter].nextTrackCommand.enabled = YES;
    [[MPRemoteCommandCenter sharedCommandCenter].nextTrackCommand addTarget:self action:@selector(forward:)];
}
```

**Comment by doriansgithub** [comment]
We’ve tried exactly that, and if it’s not on Airplay, it works fine, but on airplay, the next song looses the audio.  It’s playing, but no sound.

I tried your app and it works with no issues.

**Comment by doriansgithub** [comment]
https://developer.apple.com/documentation/uikit/uiapplication/1623078-registerforremotenotifications?language=objc <https://developer.apple.com/documentation/uikit/uiapplication/1623078-registerforremotenotifications?language=objc>

According to this, I’m supposed to register for the notifications.

"Call this method to initiate the registration process with Apple Push Notification service. If registration succeeds, the app calls your app delegate object’s  application:didRegisterForRemoteNotificationsWithDeviceToken: <https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application?language=objc> method and passes it a device token... “

**Comment by iDevelopper** [comment]
Yes this is why I asked you the code when hit next. In my app, when I tap to next, I change the radio url, create a new audio player with the url.

**Comment by doriansgithub** [comment]
You mean this?

-(void) audioPlayer:(STKAudioPlayer*)audioPlayer didFinishBufferingSourceWithQueueItemId:(NSObject*)queueItemId {

    QueueID* queueId = (QueueID*)queueItemId;
    NSLog(@"didFinishBuffering: %@", [queueId.url description]);

    MPMediaItem *item =
    [MediaPlayerNavigation nextSongFromArray:UniversallyPlayer.defaultPlayer.arrSongs
                                     isQueue:YES];
    
    [MediaPlayerNavigation fillSongInfo:item];

    [StreamingExport exportSong:item
                     completion:^(NSURL * _Nullable songURL) {
                         NSLog(@"Requeuing: %@", [queueId.url description]);
                         [self queueDataSource:[STKAudioPlayer dataSourceFromURL:songURL]
                               withQueueItemId:[[QueueID alloc] initWithUrl:queueId.url andCount:queueId.count + 0]];
                     }];

}

**Comment by patrickjquinn** [comment]
Unless this is a direct bug or issue with the framework can you guys take this to a private chat? You’re filling up my inbox 😉

Pat.

**Comment by doriansgithub** [comment]
Will do.

Patrick, use:  dorianmattar@me.com <mailto:dorianmattar@me.com>

Thanks!
