### ISSUE TITLE
MPNowPlayingInfoCenter ElapsedPlaybackTime continues increasing in background after pausing 

### ISSUE THREAD

**Issue by mitchdowney** [tumtumtum/StreamingKit#381]
I've been wrestling with this ever since iOS 11 came out, and I can't tell if I'm doing something wrong or if there is some iOS or StreamingKit bug happening.

Steps to reproduce:

– Load a locally downloaded media file into the audioPlayer, and let play for 10 seconds.
– Lock the screen and view the MPNowPlayingInfoCenter.
– Pause the audioPlayer using the headphone toggle button.
– The MPNowPlayingInfoCenter stops at the correct time.
– Leave paused for 10 seconds.
– Press the headphone toggle button to resume playback.
– The media player resumes playback from the correct time, **but** MPNowPlayingInfoCenter displays the elapsed playback time as 0:20, instead of 0:10 like it should.

It seems that the audioPlayer is ticking away increasing seconds in the background, even though it is paused.

Anyone seen this issue before? Any ideas what could be causing it?

**Comment by francosolerio** [comment]
What I would check:
Is MPNowPlayingInfoPropertyPlaybackRate set to 0.0 when updating the MPNowPlayingInfo after pausing the audio?
Is MPNowPlayingInfoPropertyElapsedPlaybackTime set to the correct time when resuming audio?

**Comment by diegostamigni** [comment]
Closing as no more feedback given.
