### ISSUE TITLE
Could StreamingKit play with SoundCloud url

### ISSUE THREAD

**Issue by gauuni** [tumtumtum/StreamingKit#382]
Hi guys, 
I'm using this lib to play streaming url from Souncloud, it looks like https://api.soundcloud.com/tracks/344134966/stream?client_id=[CLIENT_ID].

I have tried but It cannot play. Others are fine.

Can anyone help me? Thanks a lot

**Comment by Denages** [comment]
Check transferred data with debugging proxy (e.g. Charles) to find out the issue.

**Comment by gauuni** [comment]
Xcode show log some handle SSL error

**Comment by derpoliuk** [comment]
@gauuni what exactly Xcode log shows? Can you past it here?

**Comment by docterd** [comment]
This should be fixed with https://github.com/tumtumtum/StreamingKit/pull/354

**Comment by iDevelopper** [comment]
Hi @derpoliuk , @docterd 

Is it possible to merge this PR?

https://github.com/audionowdigital/StreamingKit/commit/79ee9bd1a951b9f08414f55a3503d167a57b2dce

Thanks

**Comment by derpoliuk** [comment]
@gauuni 
> This should be fixed with #354

Is your issue fixed?

**Comment by derpoliuk** [comment]
@iDevelopper 

> Is it possible to merge this PR?
>
> audionowdigital/StreamingKit@79ee9bd

Yes, please create PR in this repo and add description there what is ice cast and where it is used (or just drop links to description).

**Comment by iDevelopper** [comment]
@derpoliuk , #179

**Comment by gauuni** [comment]
I have updated pod but it still got v1.2.9

**Comment by gauuni** [comment]
@docterd , @derpoliuk , I have checked. The problem is fixed. Thanks a lot. But I cannot update pod. I have to get the zip file

**Comment by derpoliuk** [comment]
@gauuni just pushed `0.1.30` tag to CocoaPods, please update.

I'm closing the issue.
