### ISSUE TITLE
Do not allow play song immediately.

### ISSUE THREAD

**Issue by veila** [tumtumtum/StreamingKit#386]
I just want to set Datasource to Player, don't want play after that. But when I set Datasource or play:url, player always run song immediately.
Help me pls

**Comment by derpoliuk** [comment]
I have `Bool` variable that I set to `true` before I set datasource.

Than I check this variable in delegate method `audioPlayer(_:didStartPlayingQueueItemId:)` and if it is set to `true`, I pause player there.

**Comment by veila** [comment]
Thanks, I understanded

**Comment by derpoliuk** [comment]
@veila you're welcome! I'm closing this issue.
