### ISSUE TITLE
Support for shuffling?

### ISSUE THREAD

**Issue by jathu** [tumtumtum/StreamingKit#387]
Is shuffle currently supported?

**Comment by Cwoodall6** [comment]
I know I'm very late but just make a function that takes an array of ints from 0 to your song list size, import GameplayKit and call `arrayByShufflingObjects(in: array)` then you can just add the songs to the queue based on that new order.

**Comment by iDevelopper** [comment]
Without GamePlayKit:
```
extension Array {
    mutating func shuffle() {
        for _ in indices {
            sort { (_,_) in arc4random() < arc4random() }
        }
    }
}
```
