### ISSUE TITLE
error in STKAudioPlayer

### ISSUE THREAD

**Issue by effortcheep** [tumtumtum/StreamingKit#393]
when I was bliuded my xcworkspace, I get this erro in STKAudioPalyer line 325: "Cannot synthesize weak property because the current deployment target does not support weak references";

And I paste this at the end of your Podfile 
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.2'
    end
  end
end

the error disappear.

**Comment by BaseBBHuang** [comment]
I have the same the question, do you know why now ?

**Comment by tepmnthar** [comment]
#397 PR here.

**Comment by aemaddin** [comment]
same issue

**Comment by diegostamigni** [comment]
#397 PR merged, closing this issue.
