### ISSUE TITLE
MPNowPlayingInfoPropertyPlaybackRate automatically show paused when app moves to background. I dont want to pause that? , is there anything I can do?

### ISSUE THREAD

**Issue by laraibmaliknew** [tumtumtum/StreamingKit#396]

**Comment by iDevelopper** [comment]
Is your application support the background mode capability?

![2018-04-03_16-30-17](https://user-images.githubusercontent.com/1782450/38255580-74b12988-375c-11e8-983f-40f404b62405.png)

**Comment by diegostamigni** [comment]
Closing this as no more feedback given.
