### ISSUE TITLE
Control on Lockscreen using Streamingkit

### ISSUE THREAD

**Issue by onkarios** [tumtumtum/StreamingKit#400]
How to Control on Lockscreen using StreamingKit ?

**Comment by iDevelopper** [comment]
Could you elaborate? What does not work? What did you try to do?

**Comment by iDevelopper** [comment]
StreamingKit is no different from another player for this purpose.

You have to use the MPRemoteCommandCenter object, example:

```
        MPRemoteCommandCenter.shared().previousTrackCommand.isEnabled = true
        MPRemoteCommandCenter.shared().previousTrackCommand.addTarget(self, action: #selector(previous(_:)))
```

Note also that you have to enable background mode for audio (capabilities of the app) and configure and activate an audio session (AVAudioSession).

**Comment by onkarios** [comment]
Yes, I implemented. But Remote is not visible on the lock screen, notification tray.
Why does this happen?

**Comment by onkarios** [comment]
Yes. player play sound in the background.
But Remote Controller is not visible

**Comment by doriansgithub** [comment]
This happens to me sometimes, but most of the time it shows up on the lock screen.  Is your commandCenter code in the same controller as the player singleton?

**Comment by onkarios** [comment]
Yes. I used AVAudioSessionCategoryOptionMixWithOthers somewhere for testing. because of this Remote is not visible to me. 
  try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
            try! AVAudioSession.sharedInstance().setActive(true)

Now it's visible.  Thanks a lot, @iDevelopper and @doriansgithub.

**Comment by derpoliuk** [comment]
Great that issue is resolved, thanks to @iDevelopper and @doriansgithub for feedback! Closing this issue.
