### ISSUE TITLE
How to Visualize sound to show in Bar Graph?

### ISSUE THREAD

**Issue by onkarios** [tumtumtum/StreamingKit#401]
Visualize sound to show in Bar Graph. how can I use the streaming kit
?

**Comment by diegostamigni** [comment]
I'm now sure how to help you with this. What do you want to put in your graph? Samples? Packets?

Anyway, you can use `STKAudioPlayerDelegate`, get the playing item (a `STKQueueEntry` by id) and use it's property `audioStreamBasicDescription` and extract some stuff from there.
