### ISSUE TITLE
Xcode show a lot of warnings, especially with OSSpinLock

### ISSUE THREAD

**Issue by DavidGiordana** [tumtumtum/StreamingKit#404]
The framework works perfectly but Xcode shows a lot Warnings.
I tried to hide all but there is one special problem and I am worried if that can affect the usage of library. The warning is this:
'OSSpinLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock() from <os/lock.h> instead
and it is in the file STKQueueEntry.h
I hope you can help me with this.

**Comment by keba76** [comment]
Take for example OSSpinLock internalStateLock from class STKAudioPlayer.m
In initializer class set self->internalStateLock = OS_UNFAIR_LOCK_INIT;
Replace:
 OSSpinLock internalStateLock; --> os_unfair_lock internalStateLock;
OSSpinLockLock(&internalStateLock); --> os_unfair_lock_lock(&self->internalStateLock);
OSSpinLockUnlock(&internalStateLock); --> os_unfair_lock_unlock(&self->internalStateLock);

**Comment by diegostamigni** [comment]
@DavidGiordana this is in the process of being fixed. Please follow this PR #410.
