### ISSUE TITLE
Player not play audio after interruption ended 

### ISSUE THREAD

**Issue by npyadav10** [tumtumtum/StreamingKit#406]
Try to play audio getting this error: 
[aurioc] 1422: AUIOClient_StartIO failed (560557684)
How to fix this issue.

**Comment by iDevelopper** [comment]
Can you clarify as far as evidence to the contrary we can play audio with StreamingKit!

**Comment by npyadav10** [comment]
When audio is playing in my app and I open WhatsApp and play an audio note then, my app audio gets paused and resumes after the WhatsApp audio note gets finished. But, When I put WhatsApp and my app in the background then the app audio doesn't get resumed. 

Note:- I have already handled the AVAudioSessionInterruptionType. when the AVAudioSessionInterruptionType is ended then i try to resume the app audio so it gives me this error--([aurioc] 1422: AUIOClient_StartIO failed (560557684))

**Comment by tuyuan2012** [comment]
I have meet such issue！

**Comment by diegostamigni** [comment]
If you want to play in the background, first thing first is to enable those capabilities (Xcode -> Capabilities).

**Comment by npyadav10** [comment]
Thanks for reply

I fixed this issue just use this code

*func* handleAudioSessionInterruptionNotification(note: Notification) {

        *guard let typeNumber =
note.userInfo?[AVAudioSessionInterruptionTypeKey] as? NSNumber else {
return }*

*        guard let type = AVAudioSessionInterruptionType(rawValue:
typeNumber.uintValue) else { return }*



        *switch* type {



        *case* .began:

            isInterrupted = *true*

        *case* .ended:

            isInterrupted = *false*

            *let optionNumber =
note.userInfo?[AVAudioSessionInterruptionOptionKey] as? NSNumber*



*            if let number = optionNumber {*

*                let options = AVAudioSessionInterruptionOptions(rawValue:
number.uintValue)*

*                let shouldResume = options.contains(.shouldResume)*



                *switch* status {

                *case* .playing:

                    *if* shouldResume {

                        play()

                    } *else* {

                        pause(manually: *false*)

                    }



                *case* .paused(*let* manually):

                    *if* manually {

                        *// Do not resume! The user manually paused.*



                    } *else* {

                        *if* shouldResume {

                            play()

                        }

                    }



                *case* .preparing(*_*, *let* startTime):

                    status = .preparing(playWhenReady:shouldResume,
startTime: startTime)



                *case* .idle, .error(*_*), .buffering:

                    *break*

                }



            } *else* {

                *switch* status {

                *case* .playing:

                    play()



                *case* .paused(*let* manually):

                    *if* manually {

                        *// Do not resume! The user manually paused.*



                    } *else* {

                        play()

                    }



                *case* .idle, .buffering, .preparing(*_*,*_*), .error(*_*):

                    *break*

                }

            }

        }

    }


Regards,

Np Yadav
iOS Developer
LinkITes Infotech Pvt. Ltd.
+91-9754253177

**Comment by diegostamigni** [comment]
Thanks, closing this issue then.
