### ISSUE TITLE
aac

### ISSUE THREAD

**Issue by xulinlin** [tumtumtum/StreamingKit#408]
ACMP4BitStreams.cpp:565:ParseESDSBitStream:  ACMP4BitStreams::ParseESDSBitStream: the ES_Descriptor tag is incorrect

**Comment by patrickjquinn** [comment]
AAC has been a serious issue with this project for a while on a number of levels. However your issue post is not descriptive and as such can’t be addressed, could you add more information please?

**Comment by diegostamigni** [comment]
> ACMP4BitStreams.cpp:565:ParseESDSBitStream: ACMP4BitStreams::ParseESDSBitStream: the ES_Descriptor tag is incorrect

Why do you post an issue like this? How can it be helpful to us? Please be more descriptive on what the issue is and either post the entire stack trace / log or (even better) a sample project demonstrating the issue.
