### ISSUE TITLE
Setting Equalizer Effects: Bass, Treble and Mid

### ISSUE THREAD

**Issue by himanshuNetsol** [tumtumtum/StreamingKit#413]
Can you help me with how to set the bass, treble and Mid and I'm unable to understand for which particular index in equalizer array , i need to set gain to set bass , treble and Mid ??
Thanks

**Comment by diegostamigni** [comment]
> Can you help me with how to set the bass, treble and Mid and I'm unable to understand for which particular index in equalizer array , i need to set gain to set bass , treble and Mid ??
> Thanks

Hi @himanshuNetsol, you can set all your frequencies in the STKAudioPlayerOptions.equalizerBandFrequencies.
