### ISSUE TITLE
Error decoding packet

### ISSUE THREAD

**Issue by JamesonJr** [tumtumtum/StreamingKit#418]
I get NSURL to audiotrack of youtube video, and when i pass it to the playURL method my app crashs with lot of errors: [ac] ACMP4AACBaseDecoder.cpp:1337:ProduceOutputBufferList: (0x1018d2040) Error decoding packet 0: err = -1, packet length: 0

**Comment by patrickjquinn** [comment]
if you're using the M4A audio URL, this library doesn't support M4A
playback properly from YT. The encoding on their files doesn't play nicely
with StreamingKit. Use AVPlayer instead.

**Comment by JamesonJr** [comment]
i use AVPlayer, but it plays with huge delay like 5-10 seconds
I look solution for play audio instanly

**Comment by patrickjquinn** [comment]
You're not going to find a solution to do instant playback, its down to a
few things. First, instead of using the M4A url, get the URL for the 480p
video stream (code 18) and use that instead. Then use this to kick off
playback:

- (*void*)playUrl:(NSURL *)url {

    [*self* resetPlayerForNewStream];

    *self*.asset = [[AVURLAsset alloc] initWithURL:url options:*nil*];

    [*self*.asset loadValuesAsynchronouslyForKeys:@[@"playable",@"duration"]
completionHandler:^{

        dispatch_async(dispatch_get_main_queue(), ^{

            AVPlayerItem *item = [AVPlayerItem playerItemWithAsset:*self*.
asset];

            *if* (item){

                [*self*.audioPlayer replaceCurrentItemWithPlayerItem:item];

                *if* (CMTimeGetSeconds(item.duration) > 0.0){

                    *self*.audioPlayer.currentItem.
preferredForwardBufferDuration = CMTimeGetSeconds(item.duration);

                }

                *self*.audioPlayer.currentItem.
canUseNetworkResourcesForLiveStreamingWhilePaused = *YES*;

                *if* ([*self*.audioPlayer
respondsToSelector:*@selector*(playImmediatelyAtRate:)])
{

                    [*self*.audioPlayer playImmediatelyAtRate:1.0];

                } *else* {

                    [*self*.audioPlayer play];

                }

            }



        });

    }];

}

**Comment by JamesonJr** [comment]
[*self* resetPlayerForNewStream]; what this method do? and to what class it belongs?

**Comment by patrickjquinn** [comment]
Well, its a method I created to basically reset the player before passing
in a new URL. The contents of it are as follows.

    [*self*.audioPlayer.currentItem cancelPendingSeeks];

    [*self*.audioPlayer.currentItem.asset cancelLoading];

    [*self*.audioPlayer replaceCurrentItemWithPlayerItem:*nil*];

    [*self*.asset cancelLoading];

**Comment by keba76** [comment]
You need right url from youtube to playback it with streamingKit.
Check with library: https://github.com/0xced/XCDYouTubeKit. When you get url, StreamingKit will be able to playback it without problems.

**Comment by JamesonJr** [comment]
Cool guys, thanks to all it works
