### ISSUE TITLE
install 0.1.30 version have error

### ISSUE THREAD

**Issue by survivorsfyh** [tumtumtum/StreamingKit#420]
pod install 0.1.30 version have error, can`t run project.
STKAudioPlayer.m 
@implementation STKAudioPlayer
Cannot synthesize weak property because the current deployment target does not support weak references.

**Comment by keba76** [comment]
Just copy StreamingKit folder in your project.

**Comment by iDevelopper** [comment]
Change the deployment target

**Comment by diegostamigni** [comment]
@survivorsfyh you can still use pods, just set the deployment target in it. Something like:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'StreamingKit'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
```
