### ISSUE TITLE
I'm new to iOS programming. Is there any swift example app?

### ISSUE THREAD

**Issue by rodgarcialima** [tumtumtum/StreamingKit#425]
Hi all,

I'm new programming and there is only Object-C example and I was wondering if there is any Swift code example to help me.

Thank you all,

Rod

**Comment by diegostamigni** [comment]
Hi @rodgarcialima,
No, there are none at the moment I'm afraid. I'm planning to add a swift version of the iOS sample though (no ETA).

In the meanwhile, you can try converting objc to swift using some [online tool](https://objectivec2swift.com/#/home).

Closing this issue.
