### ISSUE TITLE
AUGraphStop crashes right after stream ending (iOS 14 only bug)

### ISSUE THREAD

**Issue by IlyaOst** [tumtumtum/StreamingKit#453]
While adopting my app to new iOS 14, I faced a bug that StreamingKit crashes at `stopAudioUnitWithReason` method in `status = AUGraphStop(audioGraph)` line. 
This happens only after music file ends playing, with reason == STKAudioPlayerStopReasonEof. Frequency of crash = 100%.  
Also, no description of this problem was provided by Xcode.

How can this be fixed? This is a very serious issue.

**Comment by iDevelopper** [comment]
Only happen on simulator, not on device, right?

**Comment by IlyaOst** [comment]
Unfortunately not :(
Tested this on my iPhone 6S, also have a feedback from current users who already did update on new iOS.

On simulator I have a problem simillar to https://github.com/tumtumtum/StreamingKit/issues/451. 
Absolutely can't start and have a break in `CHECK_STATUS_AND_RETURN(AUGraphInitialize(audioGraph))`.

**Comment by iDevelopper** [comment]
I forgot I had the same issue. This is what i did:
```
    func audioPlayer(_ audioPlayer: STKAudioPlayer, unexpectedError errorCode: STKAudioPlayerErrorCode) {
        DispatchQueue.main.async {
            self.pause() // UI
            self.audioPlayer.stop()
        }
    }
```

**Comment by IlyaOst** [comment]
I don't have any call for this delegate method, seems useless to me :(

**Comment by iDevelopper** [comment]
So you can use a category (extension) I wrote in the past (see #398), to get notified.

[STKAutoRecoveringHTTPDataSource+PBPrivate.zip](https://github.com/tumtumtum/StreamingKit/files/5073195/STKAutoRecoveringHTTPDataSource%2BPBPrivate.zip)

 Import STKAutoRecoveringHTTPDataSource+PBPrivate.h in your Bridging-Header.h

And for example:
```
        let dataSource = STKAudioPlayer.dataSource(from: url)
        
        (dataSource as! STKAutoRecoveringHTTPDataSource).audioPlayer = self.audioPlayer
        
        self.audioPlayer.setDataSource(dataSource, withQueueItemId: SampleQueueId(url: url, andCount: 0))
```

**Comment by LYongLiang** [comment]
Hello, have you found a solution?

**Comment by iDevelopper** [comment]
Yes, see my reply above.

**Comment by LYongLiang** [comment]
Could you update your adjustments to Git?

**Comment by iDevelopper** [comment]
@LYongLiang 

No, I wrote this category for my own use. I am neither the owner nor a contributor of this repo.

**Comment by iDevelopper** [comment]
You can submit a PR if you want...

**Comment by LYongLiang** [comment]
let dataSource = STKAudioPlayer.dataSource(from: url)
            
            (dataSource as? STKAutoRecoveringHTTPDataSource)?.audioPlayer = self.audioPlayer
            
            self.audioPlayer.setDataSource(dataSource, withQueueItemId: url as NSObject)


I tried.  In ios14 beta, it still crashes after the audio play end.

**Comment by iDevelopper** [comment]
Have you implemented the delegate function and called audioPlayer.stop()?
https://github.com/tumtumtum/StreamingKit/issues/453#issuecomment-673271182
No crash for me even in iOS 14.

**Comment by LYongLiang** [comment]
Thank you for your reply.

I wrote a demo that you can try on the device.
[Test.zip](https://github.com/tumtumtum/StreamingKit/files/5094722/Test.zip)

Crash thread:
![image](https://user-images.githubusercontent.com/15603630/90606367-532e3200-e232-11ea-8689-faaec7c211eb.png)

Crash device：
![image](https://user-images.githubusercontent.com/15603630/90606454-722cc400-e232-11ea-8876-68f6b19bd7a6.png)



Only happen on device ,  on ios14.

**Comment by iDevelopper** [comment]
I have updated Xcode beta 4 to Xcode beta 5 just before reading your comment.

Your sample does not crash.

Could you check with Xcode beta 5?

**Comment by LYongLiang** [comment]
Since Xcode12 is still in beta, So I packaged it with Xcode11.5.

I compiled with Xcode11.5, exported the IPA package, installed it on an ios14beta  device, and the crash occurred.

**Comment by LYongLiang** [comment]
Thank you very much for your help.

I have solved the problem for the time being，

In this method：
-(void) stopAudioUnitWithReason:(STKAudioPlayerStopReason)stopReasonIn

I have modified ：

    if (!(stopReasonIn == STKAudioPlayerStopReasonEof && [[UIDevice currentDevice].systemVersion compare:@"14.0"] != NSOrderedAscending)) {
        status = AUGraphStop(audioGraph);
        if (status)
        {
            [self unexpectedError:STKAudioPlayerErrorAudioSystemError];
        }
}

Thank you again.

**Comment by lixiang1994** [comment]
> 你好。似乎这个问题（在iOS14上）出现，因为`status = AUGraphStop(audioGraph);`在AUremoteIO::IOThread中调用。我找到了另一个可能的修复方法：
> 
> ```
> -(void) audioQueueFinishedPlaying:(STKQueueEntry*)entry
> {
>     STKQueueEntry* next = [bufferingQueue dequeue];
> 
>     [self processFinishPlayingIfAnyAndPlayingNext:entry withNext:next];
>     [self invokeOnPlaybackThread:^
>     {
>         [self processRunloop];
>     }];
> }
> ```
> 
> 但不能百分之百确定。很高兴听到任何改进/建议



> Hello. Seems like this problem appear (on iOS14) because `status = AUGraphStop(audioGraph);` invokes in AURemoteIO::IOThread. I've found another possible fix:
> 
> ```
> -(void) audioQueueFinishedPlaying:(STKQueueEntry*)entry
> {
>     STKQueueEntry* next = [bufferingQueue dequeue];
> 
>     [self processFinishPlayingIfAnyAndPlayingNext:entry withNext:next];
>     [self invokeOnPlaybackThread:^
>     {
>         [self processRunloop];
>     }];
> }
> ```
> 
> But not 100% sure about it. Will glad to hear any improvements/suggestions

Unfortunately, while this change fixes the crash, it causes playback to not finish properly.

**Comment by FaceWaller** [comment]
[self processFinishPlayingIfAnyAndPlayingNext:entry withNext:next]; 也放进了block里，不然会有stopReason不准的问题
```
-(void) audioQueueFinishedPlaying:(STKQueueEntry*)entry
{
    STKQueueEntry* next = [bufferingQueue dequeue];
    [self invokeOnPlaybackThread:^
    {
        [self processFinishPlayingIfAnyAndPlayingNext:entry withNext:next];
        [self processRunloop];
    }];
}
```

**Comment by ShenYj** [comment]
+ 1

```

caulk
0x000000020bec4f6c _ZN5caulk6thread4joinEv + 104

6
AudioToolbox
0x00000001c6f94c24 0x00000001c6df7000 + 1694756
7
StreamingKit
0x0000000104ce88ec -[STKAudioPlayer stopAudioUnitWithReason:] + 104
8
StreamingKit
0x0000000104ce5e7c -[STKAudioPlayer processRunloop] + 448
9
StreamingKit
0x0000000104ce5228 -[STKAudioPlayer audioQueueFinishedPlaying:] + 88
10
StreamingKit
0x0000000104ce81f4 OutputRenderCallback + 1412
11
libEmbeddedSystemAUs.dylib
0x00000002141f8c30 0x00000002141dc000 + 117808

37
libsystem_pthread.dylib
0x00000001fa5416cc _pthread_start + 148
```

**Comment by ShenYj** [comment]
> ly happen on device , on ios14.

16.3.1 (20D67) happened

**Comment by wenroudeerwa** [comment]
![image](https://user-images.githubusercontent.com/13634457/232406151-5dfecbc5-4cd5-46db-9069-9e70acf4b533.png)
I have encountered this problem, and there are guys who know what to do，thank you!

**Comment by ShenYj** [comment]
因为线上持续有这个问题，我今天刚好测试了下，只要长时间播放，不一会就会遇到

**Comment by ShenYj** [comment]
[gist](https://gist.github.com/ShenYj/48bee1bf93416ccbf4db16cbf2fb5bfe)

不想fork维护，目前通过pod hook修改了源码观察

**Comment by GJBlog** [comment]
发现 [self processFinishPlayingIfAnyAndPlayingNext:entry withNext:next]; 改动后会导致 didFinishPlayingQueueItemId 调用次数异常

**Comment by ShenYj** [comment]
> [gist](https://gist.github.com/ShenYj/48bee1bf93416ccbf4db16cbf2fb5bfe)
> 
> 不想fork维护，目前通过pod hook修改了源码观察

方案不可靠，仍然存在崩溃的问题
