### ISSUE TITLE
didFinishPlayingQueueItemId never called sometimes

### ISSUE THREAD

**Issue by fanyuexiang** [tumtumtum/StreamingKit#465]
```
- (void)audioPlayer:(STKAudioPlayer*)audioPlayer didFinishPlayingQueueItemId:(NSObject*)queueItemId withReason:(STKAudioPlayerStopReason)stopReason andProgress:(double)progress `andDuration:(double)duration
```

This method is not called by a specific playback link, just like "http://music.163.com/song/media/outer/url?id=1352930885.mp3".

Changing the play link in the demo can easily reproduce this problem

**Comment by iDevelopper** [comment]
404

**Comment by fanyuexiang** [comment]
When I copied the music link to my browser, it change to this "http://m801.music.126.net/20210708143744/3ac4d471fdfd3a3d48bd54baaaf57c62/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/4861645248/cb32/5885/dad4/967a64dadf2e96d9c225f2b66ae2a474.mp3"

The new play link in the demo can reproduce this problem too

**Comment by fanyuexiang** [comment]
allright  
just ignore it 😂😂😂
