### ISSUE TITLE
IOS LockScreen Play Pause

### ISSUE THREAD

**Issue by jerson** [tumtumtum/StreamingKit#93]
Hello, maybe this is a silly question, but I have a problem with the lock screen. 

lock screen in the pause button is presented, when I press the player is stopped, but the icon is still pause, internally paused the player using the pause method of the library but the icon does not change.

**Comment by Zulqarnain-Mustafa** [comment]
I am also stuck with same problem. It is been 3 hours i am messing with code but no solution. Please help me if any one solve this.

**Comment by dral3x** [comment]
I just face this issue and I notice that it's important to set playback rate accordilly to the actual playback state. So if the app is not playing, you should set it to 0. If playing, you should set it to 1 (generally speaking)

In swift, it looks like this
```
var info = [String: AnyObject]()
...
info[MPNowPlayingInfoPropertyPlaybackRate] = NSNumber(double: self.player.isPlaying() ? 1.0 : 0)
MPNowPlayingInfoCenter.defaultCenter().nowPlayingInfo = info
```
Hope it helps

**Comment by YogendraPatel** [comment]
Anyone find solution about play pause button image can not change in real device?
