### ISSUE TITLE
How can I create playlist and auto. play another track then current ended? 

### ISSUE THREAD

**Issue by bizibizi** [tumtumtum/StreamingKit#96]

**Comment by doriansgithub** [comment]
We can't get this player to work.  We have a fully working Media Player and wanted to implement gapless playing and EQ, but no matter what we do, the songs start to stutter after reach the 1/2 way point of the playback.

I've attached our "StreamingPlayer.m" file, which is our implementation of the STKPlayer.  Any help would be greatly appreciated.

Thanks!


[StreamingPlayer.m.zip](https://github.com/tumtumtum/StreamingKit/files/944905/StreamingPlayer.m.zip)
